# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "aws_access_key" {
  description = "AWS Access Key"
  type        = string
}

variable "aws_secret_key" {
  description = "AWS Secret Key"
  type        = string
}
